apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-retrieval-deployment
spec:
  template:
    metadata:
      labels:
        app: image-retrieval
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - image: registry.gitlab.com/openculinary/image-retrieval
        imagePullPolicy: IfNotPresent
        name: image-retrieval
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: image-retrieval
